/* vgtext.c generated by valac 0.30.0, the Vala compiler
 * generated from vgtext.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gstdio.h>
#include <stdio.h>


#define TYPE_TEXT_FILE_VIEWER (text_file_viewer_get_type ())
#define TEXT_FILE_VIEWER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TEXT_FILE_VIEWER, TextFileViewer))
#define TEXT_FILE_VIEWER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TEXT_FILE_VIEWER, TextFileViewerClass))
#define IS_TEXT_FILE_VIEWER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TEXT_FILE_VIEWER))
#define IS_TEXT_FILE_VIEWER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TEXT_FILE_VIEWER))
#define TEXT_FILE_VIEWER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TEXT_FILE_VIEWER, TextFileViewerClass))

typedef struct _TextFileViewer TextFileViewer;
typedef struct _TextFileViewerClass TextFileViewerClass;
typedef struct _TextFileViewerPrivate TextFileViewerPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _TextFileViewer {
	GtkWindow parent_instance;
	TextFileViewerPrivate * priv;
};

struct _TextFileViewerClass {
	GtkWindowClass parent_class;
};

struct _TextFileViewerPrivate {
	GtkTextView* text_view;
};


static gpointer text_file_viewer_parent_class = NULL;

GType text_file_viewer_get_type (void) G_GNUC_CONST;
#define TEXT_FILE_VIEWER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_TEXT_FILE_VIEWER, TextFileViewerPrivate))
enum  {
	TEXT_FILE_VIEWER_DUMMY_PROPERTY
};
TextFileViewer* text_file_viewer_new (void);
TextFileViewer* text_file_viewer_construct (GType object_type);
static void text_file_viewer_on_open_clicked (TextFileViewer* self);
static void _text_file_viewer_on_open_clicked_gtk_tool_button_clicked (GtkToolButton* _sender, gpointer self);
static void text_file_viewer_open_file (TextFileViewer* self, const gchar* filename);
gint text_file_viewer_main (gchar** args, int args_length1);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self);
static void text_file_viewer_finalize (GObject* obj);


static void _text_file_viewer_on_open_clicked_gtk_tool_button_clicked (GtkToolButton* _sender, gpointer self) {
	text_file_viewer_on_open_clicked ((TextFileViewer*) self);
}


TextFileViewer* text_file_viewer_construct (GType object_type) {
	TextFileViewer * self = NULL;
	GtkToolbar* toolbar = NULL;
	GtkToolbar* _tmp0_ = NULL;
	GtkStyleContext* _tmp1_ = NULL;
	GtkToolButton* open_button = NULL;
	GtkToolButton* _tmp2_ = NULL;
	GtkTextView* _tmp3_ = NULL;
	GtkTextView* _tmp4_ = NULL;
	GtkTextView* _tmp5_ = NULL;
	GtkScrolledWindow* scroll = NULL;
	GtkScrolledWindow* _tmp6_ = NULL;
	GtkTextView* _tmp7_ = NULL;
	GtkBox* vbox = NULL;
	GtkBox* _tmp8_ = NULL;
	self = (TextFileViewer*) g_object_new (object_type, NULL);
	gtk_window_set_title ((GtkWindow*) self, "Text File Viewer");
	g_object_set ((GtkWindow*) self, "window-position", GTK_WIN_POS_CENTER, NULL);
	gtk_window_set_default_size ((GtkWindow*) self, 400, 300);
	_tmp0_ = (GtkToolbar*) gtk_toolbar_new ();
	g_object_ref_sink (_tmp0_);
	toolbar = _tmp0_;
	_tmp1_ = gtk_widget_get_style_context ((GtkWidget*) toolbar);
	gtk_style_context_add_class (_tmp1_, GTK_STYLE_CLASS_PRIMARY_TOOLBAR);
	_tmp2_ = (GtkToolButton*) gtk_tool_button_new_from_stock (GTK_STOCK_OPEN);
	g_object_ref_sink (_tmp2_);
	open_button = _tmp2_;
	gtk_tool_item_set_is_important ((GtkToolItem*) open_button, TRUE);
	gtk_container_add ((GtkContainer*) toolbar, (GtkWidget*) open_button);
	g_signal_connect_object (open_button, "clicked", (GCallback) _text_file_viewer_on_open_clicked_gtk_tool_button_clicked, self, 0);
	_tmp3_ = (GtkTextView*) gtk_text_view_new ();
	g_object_ref_sink (_tmp3_);
	_g_object_unref0 (self->priv->text_view);
	self->priv->text_view = _tmp3_;
	_tmp4_ = self->priv->text_view;
	gtk_text_view_set_editable (_tmp4_, FALSE);
	_tmp5_ = self->priv->text_view;
	gtk_text_view_set_cursor_visible (_tmp5_, FALSE);
	_tmp6_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
	g_object_ref_sink (_tmp6_);
	scroll = _tmp6_;
	gtk_scrolled_window_set_policy (scroll, GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
	_tmp7_ = self->priv->text_view;
	gtk_container_add ((GtkContainer*) scroll, (GtkWidget*) _tmp7_);
	_tmp8_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
	g_object_ref_sink (_tmp8_);
	vbox = _tmp8_;
	gtk_box_pack_start (vbox, (GtkWidget*) toolbar, FALSE, TRUE, (guint) 0);
	gtk_box_pack_start (vbox, (GtkWidget*) scroll, TRUE, TRUE, (guint) 0);
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) vbox);
	_g_object_unref0 (vbox);
	_g_object_unref0 (scroll);
	_g_object_unref0 (open_button);
	_g_object_unref0 (toolbar);
	return self;
}


TextFileViewer* text_file_viewer_new (void) {
	return text_file_viewer_construct (TYPE_TEXT_FILE_VIEWER);
}


static void text_file_viewer_on_open_clicked (TextFileViewer* self) {
	GtkFileChooserDialog* file_chooser = NULL;
	GtkFileChooserDialog* _tmp0_ = NULL;
	GtkFileChooserDialog* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	GtkFileChooserDialog* _tmp6_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = (GtkFileChooserDialog*) gtk_file_chooser_dialog_new ("Open File", (GtkWindow*) self, GTK_FILE_CHOOSER_ACTION_OPEN, GTK_STOCK_CANCEL, GTK_RESPONSE_CANCEL, GTK_STOCK_OPEN, GTK_RESPONSE_ACCEPT, NULL);
	g_object_ref_sink (_tmp0_);
	file_chooser = _tmp0_;
	_tmp1_ = file_chooser;
	_tmp2_ = gtk_dialog_run ((GtkDialog*) _tmp1_);
	if (_tmp2_ == ((gint) GTK_RESPONSE_ACCEPT)) {
		GtkFileChooserDialog* _tmp3_ = NULL;
		gchar* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		_tmp3_ = file_chooser;
		_tmp4_ = gtk_file_chooser_get_filename ((GtkFileChooser*) _tmp3_);
		_tmp5_ = _tmp4_;
		text_file_viewer_open_file (self, _tmp5_);
		_g_free0 (_tmp5_);
	}
	_tmp6_ = file_chooser;
	gtk_widget_destroy ((GtkWidget*) _tmp6_);
	_g_object_unref0 (file_chooser);
}


static void text_file_viewer_open_file (TextFileViewer* self, const gchar* filename) {
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (filename != NULL);
	{
		gchar* text = NULL;
		const gchar* _tmp0_ = NULL;
		gchar* _tmp1_ = NULL;
		GtkTextView* _tmp2_ = NULL;
		GtkTextBuffer* _tmp3_ = NULL;
		GtkTextBuffer* _tmp4_ = NULL;
		_tmp0_ = filename;
		g_file_get_contents (_tmp0_, &_tmp1_, NULL, &_inner_error_);
		_g_free0 (text);
		text = _tmp1_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_free0 (text);
			goto __catch0_g_error;
		}
		_tmp2_ = self->priv->text_view;
		_tmp3_ = gtk_text_view_get_buffer (_tmp2_);
		_tmp4_ = _tmp3_;
		g_object_set (_tmp4_, "text", text, NULL);
		_g_free0 (text);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp5_ = NULL;
		GError* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp5_ = stderr;
		_tmp6_ = e;
		_tmp7_ = _tmp6_->message;
		fprintf (_tmp5_, "Error: %s\n", _tmp7_);
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
	gtk_main_quit ();
}


gint text_file_viewer_main (gchar** args, int args_length1) {
	gint result = 0;
	TextFileViewer* window = NULL;
	TextFileViewer* _tmp0_ = NULL;
	gtk_init (&args_length1, &args);
	_tmp0_ = text_file_viewer_new ();
	g_object_ref_sink (_tmp0_);
	window = _tmp0_;
	g_signal_connect ((GtkWidget*) window, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
	gtk_widget_show_all ((GtkWidget*) window);
	gtk_main ();
	result = 0;
	_g_object_unref0 (window);
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return text_file_viewer_main (argv, argc);
}


static void text_file_viewer_class_init (TextFileViewerClass * klass) {
	text_file_viewer_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (TextFileViewerPrivate));
	G_OBJECT_CLASS (klass)->finalize = text_file_viewer_finalize;
}


static void text_file_viewer_instance_init (TextFileViewer * self) {
	self->priv = TEXT_FILE_VIEWER_GET_PRIVATE (self);
}


static void text_file_viewer_finalize (GObject* obj) {
	TextFileViewer * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_TEXT_FILE_VIEWER, TextFileViewer);
	_g_object_unref0 (self->priv->text_view);
	G_OBJECT_CLASS (text_file_viewer_parent_class)->finalize (obj);
}


GType text_file_viewer_get_type (void) {
	static volatile gsize text_file_viewer_type_id__volatile = 0;
	if (g_once_init_enter (&text_file_viewer_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TextFileViewerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) text_file_viewer_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TextFileViewer), 0, (GInstanceInitFunc) text_file_viewer_instance_init, NULL };
		GType text_file_viewer_type_id;
		text_file_viewer_type_id = g_type_register_static (gtk_window_get_type (), "TextFileViewer", &g_define_type_info, 0);
		g_once_init_leave (&text_file_viewer_type_id__volatile, text_file_viewer_type_id);
	}
	return text_file_viewer_type_id__volatile;
}



